[package]
name = "zond"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
completions = ["clap", "clap_complete"]

[dependencies]
atom_syndication = "0.11"
clap = "3.1"
extract-frontmatter = "2.1"
mime_open = "0.1"
ron = "0.7"
serde = "1.0"
url = "2.2"
walkdir = "2.3"

[dependencies.chrono]
version = "~0.4"
features = ["std"]

[build-dependencies]
clap = { version = "3.1", optional = true }
clap_complete = { version = "3.1", optional = true }

[profile.release]
codegen-units = 1
strip = true
lto = true
